[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables (set in Netlify dashboard):
# BLOCKFROST_PROJECT_ID = your_blockfrost_api_key
# WEBHOOK_SECRET = your_webhook_secret
# BOT_API_URL = https://bot.swgyub.com
